### ISSUE TITLE
Browsing features fails, index listing of features is shown

### ISSUE THREAD

**Issue by dparnane** [SOFTWARE-CLINIC/featurebook#52]
Running `featurebook serve --port 3002` in our cucumber features directory serves the generated document index view, but when I click any individual feature to show its contents, nothing is shown and I get the following stack trace on node:

```
TypeError: Cannot read property 'reset' of undefined
    at Parser.parse (/..../node_modules/featurebook/node_modules/gherkin/lib/gherkin/parser.js:50:15)
    at Object.fromFileSync (/..../node_modules/featurebook/lib/gherkin-model.js:13:19)
    at Object.getFeatureSync (/..../node_modules/featurebook/lib/featurebook-api.js:75:20)
    at /..../node_modules/featurebook/lib/command-serve.js:62:25
    at Layer.handle [as handle_request] (/..../node_modules/featurebook/node_modules/express/lib/router/layer.js:95:5)
    at next (/..../node_modules/featurebook/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/..../node_modules/featurebook/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/..../node_modules/featurebook/node_modules/express/lib/router/layer.js:95:5)
    at /..../node_modules/featurebook/node_modules/express/lib/router/index.js:277:22
    at param (/..../node_modules/featurebook/node_modules/express/lib/router/index.js:349:14)
```

I didn't look too deep into the issue, but it seems that the AstBuilder might not be initalized correctly. Installation resolves the gherkin dependency as 3.1.0.

**Comment by danielpacak** [comment]
Thank you for reporting this @dparnane . Indeed there's an issue with the gherkin:3.1.0 package. The problem did not happen with gherkin:3.0.0. Anyhow I'll try to fix it shortly.

**Comment by dparnane** [comment]
@danielpacak Works like a charm now, thank you for the quick fix!
